using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PACHA_FIT.Generators;

[Generator]
public class AuthorizationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Filter methods that have attributes
        var methodDeclarations = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: (node, _) => node is MethodDeclarationSyntax m && m.AttributeLists.Count > 0,
            transform: (syntaxContext, _) => GetFunctionAuthMetadata(syntaxContext))
            .Where(x => x is not null);

        // Collect all methods metadata
        var collected = methodDeclarations.Collect();

        // Register output generation
        context.RegisterSourceOutput(collected, (spc, source) => GenerateSource(spc, source!));
    }

    private static FunctionAuthInfo? GetFunctionAuthMetadata(GeneratorSyntaxContext context)
    {
        var methodDeclaration = (MethodDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;

        string? functionName = null;
        string? roles = null;
        bool hasPachaAuthorize = false;

        foreach (var attributeList in methodDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                var symbolInfo = semanticModel.GetSymbolInfo(attribute);
                var symbol = symbolInfo.Symbol as IMethodSymbol;
                if (symbol == null) continue;

                var attributeType = symbol.ContainingType;
                var attributeTypeName = attributeType?.ToDisplayString();

                if (attributeTypeName == "Microsoft.Azure.Functions.Worker.FunctionAttribute")
                {
                    // Get the function name (the first positional argument)
                    var arg = attribute.ArgumentList?.Arguments.FirstOrDefault();
                    if (arg != null)
                    {
                        var constantValue = semanticModel.GetConstantValue(arg.Expression);
                        if (constantValue.HasValue && constantValue.Value is string name)
                        {
                            functionName = name;
                        }
                    }
                }
                else if (attributeTypeName == "PACHA_FIT.Infrastructure.Api.PachaAuthorizeAttribute")
                {
                    hasPachaAuthorize = true;
                    // Get the Roles named argument (Roles = "...")
                    var rolesArg = attribute.ArgumentList?.Arguments
                        .FirstOrDefault(a => a.NameEquals?.Name.Identifier.Text == "Roles");
                    if (rolesArg != null)
                    {
                        var constantValue = semanticModel.GetConstantValue(rolesArg.Expression);
                        if (constantValue.HasValue && constantValue.Value is string rolesValue)
                        {
                            roles = rolesValue;
                        }
                    }
                    else
                    {
                        roles = string.Empty;
                    }
                }
            }
        }

        if (functionName != null && hasPachaAuthorize)
        {
            return new FunctionAuthInfo(functionName, roles ?? string.Empty);
        }

        return null;
    }

    private static void GenerateSource(SourceProductionContext context, ImmutableArray<FunctionAuthInfo> infos)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace PACHA_FIT.Infrastructure.Api.Middlewares;");
        sb.AppendLine();
        sb.AppendLine("public static class GeneratedAuthorizationMetadata");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly Dictionary<string, string[]> PolicyMap = new(StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("    {");

        // Filter out duplicates (e.g. if the same function name is processed)
        var uniqueInfos = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var info in infos)
        {
            if (info != null)
            {
                uniqueInfos[info.FunctionName] = info.Roles;
            }
        }

        foreach (var kvp in uniqueInfos)
        {
            var functionName = kvp.Key;
            var rolesString = kvp.Value;
            
            // Format roles: e.g. new[] { "Admin", "User" }
            string rolesArrayInit;
            if (string.IsNullOrEmpty(rolesString))
            {
                rolesArrayInit = "Array.Empty<string>()";
            }
            else
            {
                var rolesParts = rolesString.Split(',')
                    .Select(r => $"\"{r.Trim()}\"");
                rolesArrayInit = $"new[] {{ {string.Join(", ", rolesParts)} }}";
            }

            sb.AppendLine($"        {{ \"{functionName}\", {rolesArrayInit} }},");
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");

        context.AddSource("GeneratedAuthorizationMetadata.g.cs", sb.ToString());
    }
}

public class FunctionAuthInfo
{
    public string FunctionName { get; }
    public string Roles { get; }

    public FunctionAuthInfo(string functionName, string roles)
    {
        FunctionName = functionName;
        Roles = roles;
    }
}
