// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PACHA_FIT.Infrastructure.Persistence;

#nullable disable

namespace PACHA_FIT.Migrations
{
    [DbContext(typeof(PachaFitContext))]
    [Migration("20260510074257_NewParamsToProduct")]
    partial class NewParamsToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("IsPostable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentAccountId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AccountId")
                        .HasName("PK__Accounts__349DA5A6FE8E4FCF");

                    b.HasIndex("ParentAccountId");

                    b.HasIndex(new[] { "Code" }, "UQ__Accounts__A25C5AA7E468A306")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.AccountingEntry", b =>
                {
                    b.Property<long>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EntryId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Credit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 4)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("CreditNoteId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Debit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 4)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<int?>("SaleId")
                        .HasColumnType("int");

                    b.HasKey("EntryId")
                        .HasName("PK__Accounti__F57BD2F79E3E7104");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreditNoteId");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("SaleId");

                    b.ToTable("AccountingEntries");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.AccountingPeriod", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeriodId"));

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ClosedBy")
                        .HasColumnType("int");

                    b.Property<bool?>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastReopenedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("LastReopenedBy")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("ReopenReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("PeriodId")
                        .HasName("PK__Accounti__E521BB16795CFA57");

                    b.HasIndex("ClosedBy");

                    b.HasIndex("LastReopenedBy");

                    b.HasIndex(new[] { "Year", "Month" }, "UQ_Period")
                        .IsUnique();

                    b.ToTable("AccountingPeriods");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.AdjustmentReason", b =>
                {
                    b.Property<int>("ReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReasonId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ReasonId")
                        .HasName("PK__Adjustme__A4F8C0E7C12F4CE2");

                    b.ToTable("AdjustmentReasons");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.AuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NewData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuditId")
                        .HasName("PK__AuditLog__A17F23980B61CE03");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A0BDE4C94FA");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex(new[] { "Slug" }, "UQ__Categori__BC7B5FB6C008D9E8")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.CreditNote", b =>
                {
                    b.Property<int>("CreditNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CreditNoteId"));

                    b.Property<string>("AdjustmentType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("DEVOLUCION");

                    b.Property<bool?>("AffectsInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("CreditNoteUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("NoteNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CreditNoteId")
                        .HasName("PK__CreditNo__AF360DC6FF05BBC4");

                    b.HasIndex("SaleId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "NoteNumber" }, "UQ__CreditNo__069440D2A3F5F451")
                        .IsUnique();

                    b.ToTable("CreditNotes");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.CreditNoteItem", b =>
                {
                    b.Property<int>("CreditNoteItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CreditNoteItemId"));

                    b.Property<int>("CreditNoteId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("UnitPriceSnapshot")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("CreditNoteItemId")
                        .HasName("PK__CreditNo__58E8CE59D1A75B4A");

                    b.HasIndex("CreditNoteId");

                    b.HasIndex("ProductId");

                    b.ToTable("CreditNoteItems");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.CustomerPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId")
                        .HasName("PK__Customer__9B556A382CD9967D");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("SaleId");

                    b.ToTable("CustomerPayments");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentMethodId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentMethodId")
                        .HasName("PK__PaymentM__DC31C1D323A7DDC2");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsWeightBased")
                        .HasColumnType("bit");

                    b.Property<int>("IvaPercentage")
                        .HasColumnType("int");

                    b.Property<string>("MainImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MainImageURL");

                    b.Property<bool?>("ManageStockDirectly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MinStockLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 4)")
                        .HasDefaultValue(5m);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ProductUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int?>("PurchaseUnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("SaleUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SKU");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Specs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("StockQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 4)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("StockUnitId")
                        .HasColumnType("int");

                    b.HasKey("ProductId")
                        .HasName("PK__Products__B40CC6CD396E8750");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PurchaseUnitId");

                    b.HasIndex("SaleUnitId");

                    b.HasIndex("StockUnitId");

                    b.HasIndex(new[] { "Slug" }, "UQ__Products__BC7B5FB697F2171C")
                        .IsUnique();

                    b.HasIndex(new[] { "Sku" }, "UQ__Products__CA1ECF0D1BF91785")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.ProductComposition", b =>
                {
                    b.Property<int>("CompositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompositionId"));

                    b.Property<int?>("BaseProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityUsed")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("CompositionId")
                        .HasName("PK__ProductC__B8E2331F8834F3C0");

                    b.HasIndex("BaseProductId");

                    b.HasIndex("ParentProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("ProductCompositions");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.PurchaseExpense", b =>
                {
                    b.Property<int>("PurchaseExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseExpenseId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("int");

                    b.HasKey("PurchaseExpenseId")
                        .HasName("PK__Purchase__D5E71DC0FA258615");

                    b.HasIndex("AccountId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseExpenses");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.PurchaseItem", b =>
                {
                    b.Property<int>("PurchaseItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseItemId"));

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TaxRateSnapshot")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("UnitCostSnapshot")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("PurchaseItemId")
                        .HasName("PK__Purchase__B48BB687CE5BA814");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseItems");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseId"));

                    b.Property<DateTimeOffset?>("PurchaseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int?>("TaxRateId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("TotalTax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 4)")
                        .HasDefaultValue(0m);

                    b.HasKey("PurchaseId")
                        .HasName("PK__Purchase__6B0A6BBE3B4C16E6");

                    b.HasIndex("SupplierId");

                    b.HasIndex("TaxRateId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1AD6C9EA39");

                    b.HasIndex(new[] { "Name" }, "UQ__Roles__737584F6E0E9C92F")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("IsCredit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Origin")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("POS");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SaleDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("SaleUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("ShippingCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 4)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Completed");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SaleId")
                        .HasName("PK__Sales__1EE3C3FFBED21984");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "OrderNumber" }, "UQ__Sales__CAC5E7433F24FD0C")
                        .IsUnique()
                        .HasFilter("[OrderNumber] IS NOT NULL");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.SaleItem", b =>
                {
                    b.Property<int>("SaleItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleItemId"));

                    b.Property<decimal>("CostPriceSnapshot")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("SaleId")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("TaxRateId")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxRateSnapshot")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("UnitPriceSnapshot")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("SaleItemId")
                        .HasName("PK__SaleItem__C605940140441B44");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.HasIndex("TaxRateId");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.StockMovement", b =>
                {
                    b.Property<long>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MovementId"));

                    b.Property<int?>("AdjustmentReasonId")
                        .HasColumnType("int");

                    b.Property<decimal>("BaseQuantityAffected")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreditNoteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InputQuantity")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("InputUnitId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<int?>("SaleId")
                        .HasColumnType("int");

                    b.Property<string>("TypeMovement")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MovementId")
                        .HasName("PK__StockMov__D18224464B22E24C");

                    b.HasIndex("AdjustmentReasonId");

                    b.HasIndex("CreditNoteId");

                    b.HasIndex("InputUnitId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("SaleId");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Attributes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SupplierId")
                        .HasName("PK__Supplier__4BE666B4EBC13550");

                    b.HasIndex(new[] { "TaxId" }, "UQ__Supplier__711BE0ADCF751AFC")
                        .IsUnique()
                        .HasFilter("[TaxId] IS NOT NULL");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.UnitOfMeasure", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("ConversionFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 8)")
                        .HasDefaultValue(1m);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UnitId")
                        .HasName("PK__UnitOfMe__44F5ECB5BFBA4837");

                    b.ToTable("UnitOfMeasures");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IdentificationNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IdentificationType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("05");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C54F69319");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105345028B452")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PACHA_FIT.src.Core.Domain.Entities.TaxRate", b =>
                {
                    b.Property<int>("TaxRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaxRateId"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("TaxRateId")
                        .HasName("PK__TaxRates__B114CEC1F99DCA29");

                    b.ToTable("TaxRates");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.Account", b =>
                {
                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.Account", "ParentAccount")
                        .WithMany("InverseParentAccount")
                        .HasForeignKey("ParentAccountId")
                        .HasConstraintName("FK__Accounts__Parent__756D6ECB");

                    b.Navigation("ParentAccount");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.AccountingEntry", b =>
                {
                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.Account", "Account")
                        .WithMany("AccountingEntries")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK__Accountin__Accou__07C12930");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.CreditNote", "CreditNote")
                        .WithMany("AccountingEntries")
                        .HasForeignKey("CreditNoteId")
                        .HasConstraintName("FK__Accountin__Credi__078C1F06");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.PurchaseOrder", "Purchase")
                        .WithMany("AccountingEntries")
                        .HasForeignKey("PurchaseId")
                        .HasConstraintName("FK__Accountin__Purch__09A971A2");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.Sale", "Sale")
                        .WithMany("AccountingEntries")
                        .HasForeignKey("SaleId")
                        .HasConstraintName("FK__Accountin__SaleI__08B54D69");

                    b.Navigation("Account");

                    b.Navigation("CreditNote");

                    b.Navigation("Purchase");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.AccountingPeriod", b =>
                {
                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.User", "ClosedByNavigation")
                        .WithMany("AccountingPeriodClosedByNavigations")
                        .HasForeignKey("ClosedBy")
                        .HasConstraintName("FK__Accountin__Close__0E391C95");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.User", "LastReopenedByNavigation")
                        .WithMany("AccountingPeriodLastReopenedByNavigations")
                        .HasForeignKey("LastReopenedBy")
                        .HasConstraintName("FK__Accountin__LastR__0F2D40CE");

                    b.Navigation("ClosedByNavigation");

                    b.Navigation("LastReopenedByNavigation");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.AuditLog", b =>
                {
                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__AuditLogs__UserI__72910220");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.Category", b =>
                {
                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.Category", "ParentCategory")
                        .WithMany("InverseParentCategory")
                        .HasForeignKey("ParentCategoryId")
                        .HasConstraintName("FK__Categorie__Paren__5070F446");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.CreditNote", b =>
                {
                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.Sale", "Sale")
                        .WithMany("CreditNotes")
                        .HasForeignKey("SaleId")
                        .IsRequired()
                        .HasConstraintName("FK__CreditNot__SaleI__69FBBC1F");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("CreditNotes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__CreditNot__UserI__6AEFE058");

                    b.Navigation("Sale");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.CreditNoteItem", b =>
                {
                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.CreditNote", "CreditNote")
                        .WithMany("CreditNoteItems")
                        .HasForeignKey("CreditNoteId")
                        .IsRequired()
                        .HasConstraintName("FK__CreditNot__Credi__6EC0713C");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.Product", "Product")
                        .WithMany("CreditNoteItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__CreditNot__Produ__6FB49575");

                    b.Navigation("CreditNote");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.CustomerPayment", b =>
                {
                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("CustomerPayments")
                        .HasForeignKey("PaymentMethodId")
                        .IsRequired()
                        .HasConstraintName("FK__CustomerP__Payme__7D0E9093");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.Sale", "Sale")
                        .WithMany("CustomerPayments")
                        .HasForeignKey("SaleId")
                        .IsRequired()
                        .HasConstraintName("FK__CustomerP__SaleI__7C1A6C5A");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.Product", b =>
                {
                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Products__Catego__5629CD9C");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.UnitOfMeasure", "PurchaseUnit")
                        .WithMany("ProductPurchaseUnits")
                        .HasForeignKey("PurchaseUnitId")
                        .HasConstraintName("FK__Products__Purcha__5812160E");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.UnitOfMeasure", "SaleUnit")
                        .WithMany("ProductSaleUnits")
                        .HasForeignKey("SaleUnitId")
                        .HasConstraintName("FK__Products__SaleUn__59063A47");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.UnitOfMeasure", "StockUnit")
                        .WithMany("ProductStockUnits")
                        .HasForeignKey("StockUnitId")
                        .HasConstraintName("FK__Products__StockU__59FA5E80");

                    b.Navigation("Category");

                    b.Navigation("PurchaseUnit");

                    b.Navigation("SaleUnit");

                    b.Navigation("StockUnit");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.ProductComposition", b =>
                {
                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.Product", "BaseProduct")
                        .WithMany("ProductCompositionBaseProducts")
                        .HasForeignKey("BaseProductId")
                        .HasConstraintName("FK__ProductCo__BaseP__03F0984C");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.Product", "ParentProduct")
                        .WithMany("ProductCompositionParentProducts")
                        .HasForeignKey("ParentProductId")
                        .HasConstraintName("FK__ProductCo__Paren__02FC7413");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.UnitOfMeasure", "Unit")
                        .WithMany("ProductCompositions")
                        .HasForeignKey("UnitId")
                        .HasConstraintName("FK__ProductCo__UnitI__04E4BC85");

                    b.Navigation("BaseProduct");

                    b.Navigation("ParentProduct");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.PurchaseExpense", b =>
                {
                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.Account", "Account")
                        .WithMany("PurchaseExpenses")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__PurchaseE__Accou__65370702");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.PurchaseOrder", "Purchase")
                        .WithMany("PurchaseExpenses")
                        .HasForeignKey("PurchaseId")
                        .IsRequired()
                        .HasConstraintName("FK__PurchaseE__Purch__6442E2C9");

                    b.Navigation("Account");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.PurchaseItem", b =>
                {
                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.Product", "Product")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__PurchaseI__Produ__68487DD7");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.PurchaseOrder", "Purchase")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("PurchaseId")
                        .HasConstraintName("FK__PurchaseI__Purch__6754599E");

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK__PurchaseO__Suppl__619B8048");

                    b.HasOne("PACHA_FIT.src.Core.Domain.Entities.TaxRate", "TaxRate")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("TaxRateId")
                        .HasConstraintName("FK__PurchaseO__TaxRa__6383C8BA");

                    b.Navigation("Supplier");

                    b.Navigation("TaxRate");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.Sale", b =>
                {
                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Sales")
                        .HasForeignKey("PaymentMethodId")
                        .HasConstraintName("FK__Sales__PaymentMe__71D1E811");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("Sales")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Sales__UserId__70DDC3D8");

                    b.Navigation("PaymentMethod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.SaleItem", b =>
                {
                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.Product", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__SaleItems__Produ__797309D9");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleId")
                        .HasConstraintName("FK__SaleItems__SaleI__787EE5A0");

                    b.HasOne("PACHA_FIT.src.Core.Domain.Entities.TaxRate", "TaxRate")
                        .WithMany()
                        .HasForeignKey("TaxRateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");

                    b.Navigation("TaxRate");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.StockMovement", b =>
                {
                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.AdjustmentReason", "AdjustmentReason")
                        .WithMany("StockMovements")
                        .HasForeignKey("AdjustmentReasonId")
                        .HasConstraintName("FK__StockMove__Adjus__7755B73D");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.CreditNote", "CreditNote")
                        .WithMany("StockMovements")
                        .HasForeignKey("CreditNoteId")
                        .HasConstraintName("FK__StockMove__Credi__7849DB76");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.UnitOfMeasure", "InputUnit")
                        .WithMany("StockMovements")
                        .HasForeignKey("InputUnitId")
                        .HasConstraintName("FK__StockMove__Input__7D439ABD");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.Product", "Product")
                        .WithMany("StockMovements")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__StockMove__Produ__7C4F7684");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.PurchaseOrder", "Purchase")
                        .WithMany("StockMovements")
                        .HasForeignKey("PurchaseId")
                        .HasConstraintName("FK__StockMove__Purch__7F2BE32F");

                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.Sale", "Sale")
                        .WithMany("StockMovements")
                        .HasForeignKey("SaleId")
                        .HasConstraintName("FK__StockMove__SaleI__7E37BEF6");

                    b.Navigation("AdjustmentReason");

                    b.Navigation("CreditNote");

                    b.Navigation("InputUnit");

                    b.Navigation("Product");

                    b.Navigation("Purchase");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.HasOne("PACHA_FIT.Infrastructure.Persistence.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Users__RoleId__4AB81AF0");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.Account", b =>
                {
                    b.Navigation("AccountingEntries");

                    b.Navigation("InverseParentAccount");

                    b.Navigation("PurchaseExpenses");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.AdjustmentReason", b =>
                {
                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.Category", b =>
                {
                    b.Navigation("InverseParentCategory");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.CreditNote", b =>
                {
                    b.Navigation("AccountingEntries");

                    b.Navigation("CreditNoteItems");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.PaymentMethod", b =>
                {
                    b.Navigation("CustomerPayments");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.Product", b =>
                {
                    b.Navigation("CreditNoteItems");

                    b.Navigation("ProductCompositionBaseProducts");

                    b.Navigation("ProductCompositionParentProducts");

                    b.Navigation("PurchaseItems");

                    b.Navigation("SaleItems");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("AccountingEntries");

                    b.Navigation("PurchaseExpenses");

                    b.Navigation("PurchaseItems");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.Sale", b =>
                {
                    b.Navigation("AccountingEntries");

                    b.Navigation("CreditNotes");

                    b.Navigation("CustomerPayments");

                    b.Navigation("SaleItems");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.Supplier", b =>
                {
                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.UnitOfMeasure", b =>
                {
                    b.Navigation("ProductCompositions");

                    b.Navigation("ProductPurchaseUnits");

                    b.Navigation("ProductSaleUnits");

                    b.Navigation("ProductStockUnits");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("PACHA_FIT.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Navigation("AccountingPeriodClosedByNavigations");

                    b.Navigation("AccountingPeriodLastReopenedByNavigations");

                    b.Navigation("AuditLogs");

                    b.Navigation("CreditNotes");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("PACHA_FIT.src.Core.Domain.Entities.TaxRate", b =>
                {
                    b.Navigation("PurchaseOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
